apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clixx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yourusername/kubernetes-manifests
    targetRevision: main
    path: apps/clixx
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
