apiVersion: apps/v1
kind: Deployment
metadata:
  name: clixx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clixx
  template:
    metadata:
      labels:
        app: clixx
    spec:
      dnsPolicy: "Default"
      containers:
        - name: clixx
          image: 957573079780.dkr.ecr.us-east-1.amazonaws.com/clixx-repository:clixx-img-2.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: "clixx-k8s-db.cazmwu8usa6n.us-east-1.rds.amazonaws.com"
            - name: WORDPRESS_DB_NAME
              value: "wordpressdb"
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: db_user
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: db_password
            - name: WP_HOME
              value: "http://app.stack-mayowa.com"
            - name: WP_SITEURL
              value: "http://app.stack-mayowa.com"
      imagePullSecrets:
        - name: ecr-creds