apiVersion: v1
kind: Service
metadata:
  name: clixx-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: clixx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080